apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: ddis-asteroid--usernaut-rhplatformtest
    app.kubernetes.io/managed-by: kustomize
  name: dataverse-aggregate-mygroup
  namespace: ddis-asteroid--usernaut-rhplatformtest
spec:
  group_name: aif-dataverse-aggregate-mygroup
  members:
   users:
    - subhatta
    - bdebnath
    - 783m
    - 5dlb
  group_params: []
  backends: []
  